### ISSUE TITLE
typo in Data_Update_speed

### ISSUE THREAD

**Issue by eumaios** [Risele/SHT3x#2]
There is a typo in Data_Update_speed line 27. Replace Sensor_H with Sensor_FAST.
`Serial.print("F: "); Serial.print(Sensor_H.GetRelHumidity(),2);`
should be
`Serial.print("F: "); Serial.print(Sensor_FAST.GetRelHumidity(),2);`

**Comment by Risele** [comment]
Thanks for notice!

Updated.
