### ISSUE TITLE
Data_Update_speed: no values (only zeros)

### ISSUE THREAD

**Issue by eumaios** [Risele/SHT3x#3]
The arduino only returns "zero" values for all sensors and all speeds. What is wrong? (sketch operations mode working...)

Output on serial monitor:

`Temperature, �`
`F: 0.00 | S: 0.00`
`Relative Humidity, %`
`F: 0.00 | S: 0.00`
`Temperature, �`
`F: 0.00 | S: 0.00`
`Relative Humidity, %`
`F: 0.00 | S: 0.00`

**Comment by Risele** [comment]
Check for errors with GetError() method.
The value you will receive will be corresponding to enum Errors:
`enum Errors`
`{`
`	noError 		= 0,`
`	Timeout 		= 1,`
`	DataCorrupted 	= 2,`
`	WrongAddress	= 3,`
`	//I2C errors`
`	TooMuchData 	= 4,`
`	AddressNACK 	= 5,`
`	DataNACK 		= 6,`
`	OtherI2CError 	= 7,`
`	UnexpectedError = 8`
`}`


Have you specified right addresses of both sensors?

**Comment by eumaios** [comment]
GetError() gives "0".

But now I found out that the sketch works, if I add the following two lines to the loop.

`Sensor_FAST.UpdateData();`
`Sensor_SLOW.UpdateData();`

**Comment by Risele** [comment]
Oh! 
I forgot them when copy-pasted code from one example to another, my apologize. 
Added to the example and readme.
