### ISSUE TITLE
Calibration

### ISSUE THREAD

**Issue by oxedgar** [Risele/SHT3x#7]
Hello,

Thank you for your job. 
Can you tell me how i can determine (calculate) factors and shift like your exemple:

`SHT3x::CalibrationFactors TemperatureCalibration;
  TemperatureCalibration.Factor = -1.;
  TemperatureCalibration.Shift = -1000.;
  /*And than use Kelvin, muhaha!
  Ok, that was a joke. Here are real values from my expeirence (Celsius):
  my SHT30 and trusted instrument have shown 
  (temperature conditions were similar, we tested it over humidity changes):
  SHT30: 23.6 ; 25.1;
  TrIns: 22.3 ; 23.7;
  So, the overcalibraion equation is:
  Trusted_Instrument = SHT30 * 0.9333 + 0.2733,
  so 
  */
  TemperatureCalibration.Factor = 0.9333; 
  TemperatureCalibration.Shift  = 0.2733;
  Sensor.SetTemperatureCalibrationFactors(TemperatureCalibration);`

Thank you

**Comment by tmm1** [comment]
I am also curious about this. I thought the SHT3x was factory calibrated already?

**Comment by Risele** [comment]
SHT30 is pretty good sensor, but it is not metrology instrument. Sometimes you need more precise data as I had. 
So, I used a metrology calibrated instruments to measure, how SHT30 values differ from my trusted measurements. The difference was not so big (values in example are real), but it was not acceptable for me. So, I placed the sensor and trusted instrument to the same conditions simultaneously and measured values at some temperature points. After that I checked that difference is linear and calculated values for calibration with simple linear function.
